# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmen', '0002_auto_20170809_1107'),
        ('recruitmen', '0003_auto_20171003_1756'),
    ]

    operations = [
    ]
